packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  esbuild: true
  prisma: true

catalog:
  typescript: ^5.7.2
  vitest: ^2.1.8
  rimraf: ^6.0.1
  "@types/node": ^22.10.2
  zod: ^3.24.1
  pino: ^9.6.0
  fastify: ^5.2.0
  "@fastify/multipart": ^9.0.1
  jose: ^5.9.6
  prisma: ^6.1.0
  "@prisma/client": ^6.1.0
  tsx: ^4.19.2
  react: ^18.3.1
  react-dom: ^18.3.1
  "@types/react": ^18.3.18
  "@types/react-dom": ^18.3.5
  "@testing-library/react": ^16.1.0
  "@testing-library/jest-dom": ^6.6.3
  jsdom: ^25.0.1
  vite: ^6.0.7
  "@vitejs/plugin-react": ^4.3.4
  "@tauri-apps/cli": ^2.1.0
  "@tauri-apps/api": ^2.1.1
